#= /*
* This file is part of OpenModelica.
*
* Copyright (c) 1998-2026, Open Source Modelica Consortium (OSMC),
* c/o Linköpings universitet, Department of Computer and Information Science,
* SE-58183 Linköping, Sweden.
*
* All rights reserved.
*
* THIS PROGRAM IS PROVIDED UNDER THE TERMS OF AGPL VERSION 3 LICENSE OR
* THIS OSMC PUBLIC LICENSE (OSMC-PL) VERSION 1.8.
* ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS PROGRAM CONSTITUTES
* RECIPIENT'S ACCEPTANCE OF THE OSMC PUBLIC LICENSE OR THE GNU AGPL
* VERSION 3, ACCORDING TO RECIPIENTS CHOICE.
*
* The OpenModelica software and the OSMC (Open Source Modelica Consortium)
* Public License (OSMC-PL) are obtained from OSMC, either from the above
* address, from the URLs:
* http://www.openmodelica.org or
* https://github.com/OpenModelica/ or
* http://www.ida.liu.se/projects/OpenModelica,
* and in the OpenModelica distribution.
*
* GNU AGPL version 3 is obtained from:
* https://www.gnu.org/licenses/licenses.html#GPL
*
* This program is distributed WITHOUT ANY WARRANTY; without
* even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE, EXCEPT AS EXPRESSLY SET FORTH
* IN THE BY RECIPIENT SELECTED SUBSIDIARY LICENSE CONDITIONS OF OSMC-PL.
*
* See the full OSMC Public License conditions for more details.
*
*/ =#

#= Author: John Tinnerholm, partially automatically translated =#

#=
TODO:
Move Var s.t it is close to the struct that defines it.
Make all datatypes here immutable. I think having VAR as a immutable struct is better.
=#

"""
  Backend intermediate representation (BDAE) for the OMBackend pipeline.

  A `BACKEND_DAE` is the lowered form of a flattened Modelica model. It splits
  variables into two pools (unknown states / algebraic, and known parameters /
  constants) and splits equations into ordered equations plus a bucket of simple
  alias equations that have already been removed from the main equation set.
"""
module BDAE

import OMFrontend

using MetaModelica
using ExportAll

#=
  Predeclaration of mutable recursive types.

  `EqSystem` and `Variables` are retained as dangling abstract types because
  `BDAEUtil.jl` and `Causalize.jl` still carry type annotations referencing
  them. Those annotations guard legacy code paths that never fire at runtime
  because no concrete subtype is ever constructed; removing the forward
  declarations would break compilation until those sites are refactored.
=#
@UniontypeDecl EqSystem
@UniontypeDecl Variables

"""
  Abstract supertype of the concrete backend variable record `VAR`.
  Exists so other subsystems can accept `Var`-typed arguments without
  pinning the concrete record layout.
"""
@UniontypeDecl Var

"""
  Classification of a backend variable.

  Variants actually constructed by the lowering / causalization pipeline:

  - `VARIABLE` — default algebraic unknown.
  - `STATE(index, derName, natural)`:
    - `index`: how often this state was differentiated.
    - `derName`: name of the derivative component reference, if known.
    - `natural`: `false` if the state was forced by `StateSelect.always` /
      `StateSelect.prefer` or generated by index reduction.
  - `STATE_DER` — state derivative (`der(x)`).
  - `DUMMY_DER` — dummy derivative introduced by Pantelides index reduction.
  - `DUMMY_STATE` — dummy state paired with a `DUMMY_DER`.
  - `DISCRETE` — discrete-time variable (changes only on events).
  - `PARAM` — parameter (constant for a single simulation run).
  - `CONST` — compile-time constant.

  Additional variants present for OpenModelica-compat but not produced by
  this backend (kept so `backendDump.jl` can pretty-print externally
  supplied BDAE fragments): `CLOCKED_STATE(previousName, isStartFixed)`,
  `EXTOBJ(fullClassName)`, `JAC_VAR`, `JAC_DIFF_VAR`, `SEED_VAR`,
  `OPT_CONSTR`, `OPT_FCONSTR`, `OPT_INPUT_WITH_DER`, `OPT_INPUT_DER`,
  `OPT_TGRID`, `OPT_LOOP_INPUT(replaceExp)`, `ALG_STATE`, `ALG_STATE_OLD`,
  `DAE_RESIDUAL_VAR`, `DAE_AUX_VAR`, `LOOP_ITERATION`, `LOOP_SOLVED`.
"""
@UniontypeDecl VarKind

"""
  Per-equation kind tag used inside [`EquationAttributes`](@ref).

  Variants: `DYNAMIC_EQUATION` (dynamic / simulation-time) and
  `UNKNOWN_EQUATION_KIND` (placeholder used before classification).
"""
@UniontypeDecl EquationKind

"""
  Flags controlling which simulation stages an equation contributes to.

  Single variant:

  - `EVALUATION_STAGES(dynamicEval, algebraicEval, zerocrossEval, discreteEval)`
    — four `Bool` flags, one per stage.
"""
@UniontypeDecl EvaluationStages

"""
  Equation metadata wrapper.

  Variants:

  - `EQUATION_ATTRIBUTES(differentiated, kind, evalStages)`:
    - `differentiated`: `true` if the equation was produced by symbolic
      differentiation. Guards against being differentiated twice.
    - `kind`: an [`EquationKind`](@ref) tag.
    - `evalStages`: an [`EvaluationStages`](@ref) flag set.
  - `NO_ATTRIBUTES` — sentinel used when attributes are unknown or not
    yet assigned.
"""
@UniontypeDecl EquationAttributes

"""
  Sum type for backend equations.

  Variants and their fields:

  - `EQUATION(lhs, rhs, source, attributes)` — plain equality `lhs = rhs`.
  - `ARRAY_EQUATION(dimSize, left, right, source, attr, recordSize)` —
    array-shaped equation. `dimSize` holds the array dimension sizes;
    `recordSize` is `NONE()` for non-record arrays.
  - `SOLVED_EQUATION(componentRef, exp, source, attr)` — explicitly solved
    form `componentRef = exp` (currently no code path constructs this; see
    audit entry in `REPORTS/2026-04-17_BDAE_audit/audit.md`).
  - `RESIDUAL_EQUATION(exp, source, attr)` — `0 = exp` residual form;
    produced by `Causalize.residualizeEveryEquation`, not the frontend.
  - `ALGORITHM(size, alg, source, expand, attr)` — algorithm section.
    `size` is the number of equations the block stands in for; `expand`
    is inherited from `DAE.Expand` and tells the code generator whether
    to expand array crefs inside the body.
  - `WHEN_EQUATION(size, whenEquation, source, attr)` — ordinary `when`.
  - `STRUCTURAL_WHEN_EQUATION(size, whenEquation, source, attr)` — `when`
    whose body contains a `RECOMPILATION` or `AGENTIC_RECOMPILATION`
    operator, marking it as a trigger for VSS structural change.
  - `COMPLEX_EQUATION(size, left, right, source, attr)` — record-typed
    equality; `size` counts the scalarized fields.
  - `IF_EQUATION(conditions, eqnstrue, eqnsfalse, source, attr)` — each
    condition maps one-to-one to a branch in `eqnstrue`; `eqnsfalse` holds
    the else branch.
  - `FOR_EQUATION(iter, start, stop, body, source, attr)` — ranged loop
    equation. No frontend path currently emits it.
  - `DUMMY_EQUATION` — placeholder used when a NORETCALL cannot be lowered.
  - `ASSERT_EQUATION(condition, message, level, source)`.
  - `INITIAL_STRUCTURAL_STATE(initialState)` — records the initial mode
    name for a variable-structure system.
  - `BRANCH(ar, br)` — `Connections.branch(ar, br)`.
  - `STRUCTURAL_IF_EQUATION(ifEquation)` — DOCC if-equation preserved as a
    frontend `EQUATION_IF` so the runtime can replay the branch choice.
  - `STRUCTURAL_TRANSITION(fromState, toState, transitionCondition)` —
    VSS transition; a structural callback is generated from the condition.
    (Name is a historical typo preserved across the codebase.)
"""
@UniontypeDecl Equation

"""
  Condition-guarded block of [`WhenOperator`](@ref) statements.

  Single variant:

  - `WHEN_STMTS(condition, whenStmtLst, elsewhenPart)`:
    - `condition`: the when-condition expression.
    - `whenStmtLst`: list of `WhenOperator` statements to run on trigger.
    - `elsewhenPart`: chained `elsewhen`, `NONE()` or `SOME(WHEN_EQUATION)`.
"""
@UniontypeDecl WhenEquation

"""
  Statements permitted inside a `when` clause.

  Variants and their fields:

  - `ASSIGN(left, right, source)` — `left = right` fired on the trigger.
  - `REINIT(stateVar, value, source)` — `reinit(stateVar, value)`.
    `stateVar` is stored as a `DAE.CREF` (rather than a raw
    `ComponentRef`) to unify expression traversal.
  - `ASSERT(condition, message, level, source)`.
  - `TERMINATE(message, source)`.
  - `NORETCALL(exp, source)` — no-return call inside a `when`.
  - `RECOMPILATION(componentToChange, newValue)` — VSS structural change
    trigger; emits a recompile with the given component set to `newValue`.
    Only meaningful inside a `when` equation.
  - `AGENTIC_RECOMPILATION(componentsToChange, prompt, initialEquations)`
    — agent-driven recompilation. New values are determined at runtime by
    an external agent. `prompt` forwards a natural-language hint; the
    serialized `initialEquations` string supplies constraint equations the
    agent must honour.
"""
@UniontypeDecl WhenOperator

import Absyn
import DAE
import SCode

"""
  Pair of a component reference and its ordinal index within an equation
  system. Used by matching / indexing helpers to convert between symbolic
  names and integer slots.
"""
struct CREFINDEX
  cref::DAE.ComponentRef
  index::Int
end

"""
  The concrete backend variable record.

  Fields:
  - `varName`: the component reference this variable stands for.
  - `varKind`: state / algebraic / parameter / constant / discrete / ...
  - `varDirection`: input, output, or bidirectional.
  - `varType`: scalar built-in type or enumeration type.
  - `bindExp`: optional binding expression (e.g. parameter default).
  - `arryDim`: array dimensions when the variable is not yet scalarized.
  - `source`: origin metadata (file, line, comment) from the front end.
  - `values`: optional built-in attribute bundle (start, min, max, nominal, ...).
  - `tearingSelectOption`: legacy slot retained for binary compatibility;
    tearing is not currently performed inside OMBackend.
  - `connectorType`: flow / stream / unspecified / not-a-connector.
  - `unreplaceable`: guard against being substituted out by alias elimination.
"""
mutable struct VAR <: Var
  varName::DAE.ComponentRef
  varKind::VarKind
  varDirection::DAE.VarDirection
  varType::DAE.Type
  bindExp::Option{DAE.Exp}
  arryDim::List{DAE.Dimension}
  source::DAE.ElementSource
  values::Option{DAE.VariableAttributes}
  tearingSelectOption::Option
  connectorType::DAE.ConnectorType
  unreplaceable::Bool
end

"""
  Convenience constructor: a bidirectional, non-connector, replaceable VAR
  with no binding, no dimensions, and no attribute bundle.
"""
VAR(varName,varKind,varType) =
  let
    VAR(varName, varKind, DAE.BIDIR(), varType, NONE(), nil, DAE.emptyElementSource,
        NONE(), NONE(), DAE.NON_CONNECTOR(), true #= Unreplaceable =#)
  end

"""
  An independent system of equations together with its variables.

  Each structural submodel (VSS branch, DOCC subsystem) becomes one
  `EQSYSTEM`. The `simpleEquations` field holds alias equations that have
  already been removed from the main equation list via alias elimination;
  they are kept so downstream stages can recover the original mapping.

  Fields:
  - `name`: identifier for the subsystem (typically the model or
    submodel class name).
  - `orderedVars`: states and algebraic unknowns in declaration order.
    Parameters and constants live on [`SHARED`](@ref) instead.
  - `orderedEqs`: the main equation list, aligned 1:1 with `orderedVars`
    after matching.
  - `simpleEquations`: alias equations already eliminated from the main
    list (kept for round-trip / reporting).
  - `initialEqs`: equations that only apply at initialization.
"""
mutable struct EQSYSTEM
  name::String
  orderedVars::Vector{VAR}
  orderedEqs::Vector{Equation}
  simpleEquations::Vector{Equation}
  initialEqs::Vector{Equation}
end

"""
  State shared between all equation systems of a single model.

  Fields:
  - `globalKnownVars`: parameters / constants visible in every subsystem.
  - `localKnownVars`: parameters / constants scoped to a specific submodel.
  - `metaModel`: optional reference to the surrounding meta-model; `NONE()`
    for non-VSS models.
  - `flatModel`: optional reference to the flat model being translated.
    Used by VSS recompilation paths.
  - `DOCC_equations`: dynamic-if equations from the Dynamic Overconstrained
    Connector option.
"""
struct SHARED
  globalKnownVars::Vector{VAR}
  localKnownVars::Vector{VAR}
  metaModel::Option{SCode.CLASS}
  flatModel::Option{OMFrontend.Frontend.FlatModel}
  DOCC_equations::Vector{Equation}
end

"""
  Top-level lowered DAE container: one or more `EQSYSTEM`s plus `SHARED`
  knowledge. This is what the causalization pipeline consumes and what the
  code generator translates into an MTK `ODESystem`.
"""
mutable struct BACKEND_DAE
  name::String
  eqs::Vector{EQSYSTEM}
  shared::SHARED
end

@Uniontype VarKind begin
  @Record VARIABLE begin
  end

  @Record STATE begin
    index::Int
    derName::Option{DAE.ComponentRef}
    natural::Bool
  end

  @Record STATE_DER begin
  end

  @Record DUMMY_DER begin
  end

  @Record DUMMY_STATE begin
  end

  @Record CLOCKED_STATE begin
    previousName::DAE.ComponentRef
    isStartFixed::Bool
  end

  @Record DISCRETE begin
  end

  @Record PARAM begin
  end

  @Record CONST begin
  end

  @Record EXTOBJ begin
    fullClassName::Absyn.Path
  end

  @Record JAC_VAR begin
  end

  @Record JAC_DIFF_VAR begin
  end

  @Record SEED_VAR begin
  end

  @Record OPT_CONSTR begin
  end

  @Record OPT_FCONSTR begin
  end

  @Record OPT_INPUT_WITH_DER begin
  end

  @Record OPT_INPUT_DER begin
  end

  @Record OPT_TGRID begin
  end

  @Record OPT_LOOP_INPUT begin
    replaceExp::DAE.ComponentRef
  end

  @Record ALG_STATE begin
  end

  @Record ALG_STATE_OLD begin
  end

  @Record DAE_RESIDUAL_VAR begin
  end

  @Record DAE_AUX_VAR begin
  end

  @Record LOOP_ITERATION begin
  end

  @Record LOOP_SOLVED begin
  end
end

"""
  Zero-argument constructor for a first-order, natural differential state with
  no known derivative name yet. Equivalent to `STATE(0, NONE(), false)`.
"""
STATE() = let
  STATE(0, NONE(), false)
end

@Uniontype EquationKind begin
  @Record DYNAMIC_EQUATION begin

  end

  @Record UNKNOWN_EQUATION_KIND begin

  end
end

@Uniontype EvaluationStages begin
  @Record EVALUATION_STAGES begin
    dynamicEval::Bool
    algebraicEval::Bool
    zerocrossEval::Bool
    discreteEval::Bool
  end
end

"Default `EvaluationStages` value: all stages off."
const defaultEvalStages = EVALUATION_STAGES(false, false, false, false)::EvaluationStages

@Uniontype EquationAttributes begin
  @Record EQUATION_ATTRIBUTES begin
    differentiated::Bool
    kind::EquationKind
    evalStages::EvaluationStages
  end
  @Record NO_ATTRIBUTES begin
  end
end

"Dynamic-equation attribute bundle with all stage flags off."
const EQ_ATTR_DEFAULT_DYNAMIC = EQUATION_ATTRIBUTES(false, DYNAMIC_EQUATION(), defaultEvalStages)::EquationAttributes

"Placeholder attribute bundle used until an equation's kind is refined."
const EQ_ATTR_DEFAULT_UNKNOWN = EQUATION_ATTRIBUTES(false, UNKNOWN_EQUATION_KIND(), defaultEvalStages)::EquationAttributes

@Uniontype Equation begin
  @Record EQUATION begin
    lhs::DAE.Exp
    rhs::DAE.Exp
    source::DAE.ElementSource
    attributes::EquationAttributes
  end

  @Record ARRAY_EQUATION begin
    dimSize::Vector{Int64}
    left::DAE.Exp
    right::DAE.Exp
    source::DAE.ElementSource
    attr::EquationAttributes
    recordSize::Option{Int}
  end

  @Record SOLVED_EQUATION begin
    componentRef::DAE.ComponentRef
    exp::DAE.Exp
    source::DAE.ElementSource
    attr::EquationAttributes
  end

  @Record RESIDUAL_EQUATION begin
    exp::DAE.Exp
    source::DAE.ElementSource
    attr::EquationAttributes
  end

  @Record ALGORITHM begin
    size::Int
    alg::DAE.Algorithm
    source::DAE.ElementSource
    expand::DAE.Expand
    attr::EquationAttributes
  end

  @Record WHEN_EQUATION begin
    size::Int
    whenEquation::WhenEquation
    source::DAE.ElementSource
    attr::EquationAttributes
  end

  #= Body of an `algorithm when initial() then ... end when` clause. Distinct
     from WHEN_EQUATION so init-time bodies stay separated from runtime
     when-equations through the pipeline. =#
  @Record INITIAL_WHEN_EQUATION begin
    size::Int
    whenEquation::WhenEquation
    source::DAE.ElementSource
    attr::EquationAttributes
  end

  @Record STRUCTURAL_WHEN_EQUATION begin
    size::Int
    whenEquation::WhenEquation
    source::DAE.ElementSource
    attr::EquationAttributes
  end

  @Record COMPLEX_EQUATION begin
    size::Int
    left::DAE.Exp
    right::DAE.Exp
    source::DAE.ElementSource
    attr::EquationAttributes
  end

  @Record IF_EQUATION begin
    conditions::List{DAE.Exp}
    eqnstrue::List{List{Equation}}
    eqnsfalse::List{Equation}
    source::DAE.ElementSource
    attr::EquationAttributes
  end

  @Record FOR_EQUATION begin
    iter::DAE.Exp
    start::DAE.Exp
    stop::DAE.Exp
    body::Equation
    source::DAE.ElementSource
    attr::EquationAttributes
  end

  @Record DUMMY_EQUATION begin
  end

  @Record ASSERT_EQUATION begin
    condition::DAE.Exp
    message::DAE.Exp
    level::DAE.Exp
    source::DAE.ElementSource
  end

  @Record INITIAL_STRUCTURAL_STATE begin
    initialState::String
  end

  @Record BRANCH begin
    ar::DAE.Exp
    br::DAE.Exp
  end

  @Record STRUCTURAL_IF_EQUATION begin
    ifEquation::OMFrontend.Frontend.EQUATION_IF
  end

  @Record STRUCTURAL_TRANSITION begin
    fromState::String
    toState::String
    transitionCondition::DAE.Exp
  end
end

@Uniontype WhenEquation begin
  @Record WHEN_STMTS begin
    condition::DAE.Exp
    whenStmtLst::List{WhenOperator}
    elsewhenPart::Option{WHEN_EQUATION}
  end
end

@Uniontype WhenOperator begin
  @Record ASSIGN begin
    left::DAE.Exp
    right::DAE.Exp
    source::DAE.ElementSource
  end

  @Record REINIT begin
    stateVar::DAE.CREF
    value::DAE.Exp
    source::DAE.ElementSource
  end

  @Record ASSERT begin
    condition::DAE.Exp
    message::DAE.Exp
    level::DAE.Exp
    source::DAE.ElementSource
  end

  @Record TERMINATE begin
    message::DAE.Exp
    source::DAE.ElementSource
  end

  @Record NORETCALL begin
    exp::DAE.Exp
    source::DAE.ElementSource
  end

  @Record RECOMPILATION begin
    componentToChange::DAE.CREF
    newValue::DAE.Exp
  end

  @Record AGENTIC_RECOMPILATION begin
    componentsToChange::Vector{DAE.CREF}
    prompt::Option{String}
    initialEquations::Option{String}
  end
end

@exportAll()
end
